#docker postgres host
#flyway:
spring:
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/black_mulberry
  flyway:
    url: jdbc:postgresql://dbpostgresql:5432/black_mulberry
logging:
  level:
    root: debug
    com.mulberry: debug