spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/black_mulberry
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#flyway:
  flyway:
    mixed: true
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/black_mulberry
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true
server:
  servlet:
    contextPath: /api
  port: 8000
jwt:
      secret: k205j@dkjf0%^@
      expiration: 330000
